_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
architecture:
    value: ResNet18
batch_size:
    value: 32
dataset:
    value: robot_state
epochs:
    value: 50
learning_rate:
    value: 0.001
optimizer:
    value: Adam
scheduler:
    value: ReduceLROnPlateau
weight_decay:
    value: 1e-05
