wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750824583
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.8.20
      5: 0.19.11
      8:
      - 5
      13: linux-x86_64
architecture:
  desc: null
  value: ResNet18
dataset:
  desc: null
  value: robot_state
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 1.0e-05
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: ReduceLROnPlateau
